[package]
name = "runtime"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true
api.workspace = true
spin.workspace = true
talc.workspace = true

[lints]
workspace = true
