[package]
name = "kernel"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true
api.workspace = true
runtime.workspace = true
talc.workspace = true
spin.workspace = true
lazy_static.workspace = true