[package]
name = "compiler"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true
api.workspace = true
runtime.workspace = true

thiserror.workspace = true
anyhow.workspace = true
chumsky.workspace = true
miette.workspace = true
